### ISSUE TITLE
Design a logo for certificate generator 

### ISSUE THREAD

**Issue by Aniket762** [Webwiznitr/Project-celadon#24]
A cool logo 😎

**Comment by AlexBobrov** [comment]
I would like to work, please assign the issue to me.

What logo do you need(.png .svg .ico)?

**Comment by kartikagarwal9** [comment]
As I am experienced in making logos, you can try me, I would love to contribute. I can make any type of logo. I will be sending a PR , you may consider it @Aniket762

**Comment by kartikagarwal9** [comment]
I have submitted a Pull Request , please consider it @Aniket762

**Comment by calderaricaio** [comment]
Hi I was going to create the logo, since there's also other people commenting and trying to create it, should I still do it?

**Comment by calderaricaio** [comment]
Here is my take on this. I created a name based on the "Certificate Generator" name. It's a mix that is short and simple so it can be applied in many places also with a simple icon that can be used in small places like favicons or app icons.

In my opinion we can remove the "Certificate Generator" under the name but I added it just for reference.

![Screen Shot 2020-10-14 at 22 48 58](https://user-images.githubusercontent.com/542722/96067630-97276700-0e70-11eb-980a-2e38443a4407.png)

Let me know what you think!

**Comment by Aniket762** [comment]
> Here is my take on this. I created a name based on the "Certificate Generator" name. It's a mix that is short and simple so it can be applied in many places also with a simple icon that can be used in small places like favicons or app icons.
> 
> In my opinion we can remove the "Certificate Generator" under the name but I added it just for reference.
> 
> ![Screen Shot 2020-10-14 at 22 48 58](https://user-images.githubusercontent.com/542722/96067630-97276700-0e70-11eb-980a-2e38443a4407.png)
> 
> Let me know what you think!

Looks so cool 😍. It will be great if you can create the PR

**Comment by calderaricaio** [comment]
I will be adding the logo and files soon!
I will create a new PR once the current is completed.

![logo-preview](https://user-images.githubusercontent.com/542722/96194235-59821700-0f20-11eb-8326-92210410285b.png)

**Comment by calderaricaio** [comment]
@Aniket762 Hi! Here's the PR for the Logo and files: https://github.com/Webwiznitr/Project-celadon/pull/30

**Comment by calderaricaio** [comment]
@Aniket762 I did a page redesign, adding the new logo and also included a file upload for the signature.
Take a look and see if you like it:

![Home-Page](https://user-images.githubusercontent.com/542722/96276086-eec8ee00-0fa8-11eb-8ad4-05031b8d3226.png)
