### ISSUE TITLE
Add header 

### ISSUE THREAD

**Issue by Aniket762** [Webwiznitr/Project-celadon#5]
Something cool is preferable. Just add the screenshots of the element which you are adding.

**Comment by calderaricaio** [comment]
Do you need design for this as well?

**Comment by deb2000-sudo** [comment]
Hey @calderaricaio ,it will be prefarable if you send designs over here.

**Comment by calderaricaio** [comment]
Sure I will do!

**Comment by calderaricaio** [comment]
Do you have a logo already?

**Comment by Aniket762** [comment]
@calderaricaio  The one which is present in the repo is our logo. But use any random logo as with certificate generated we will replace the logo

**Comment by Aniket762** [comment]
@calderaricaio the one which is present in the repo is our logo

**Comment by rahuldhangar** [comment]
@Aniket762 I have created an intuitive header which matches the footer (with wave animation) Please check Screenshot.
![image](https://user-images.githubusercontent.com/7106661/95256802-eeaa4f00-0840-11eb-8f3e-bc1ce6a62b32.png)

If this looks good, I can open PR. Kindly let me know your views. Check it here: [CodePen - Rahul Dhangar](https://codepen.io/rahuldhangar/pen/dyXybPo)

**Comment by Aniket762** [comment]
Awsome dude 😍 
@rahuldhangar create the PR

**Comment by rahuldhangar** [comment]
@Aniket762 Thanks! Please assign it to me. Creating PR.
