### ISSUE TITLE
Add footer 

### ISSUE THREAD

**Issue by Aniket762** [Webwiznitr/Project-celadon#6]
Something cool is preferable. Just add the screenshots of the element which you are adding.

**Comment by calderaricaio** [comment]
Do you need design for this as well?

**Comment by rahuldhangar** [comment]
@Aniket762 Where should the screenshots be added? inside PR? or in comment?

**Comment by deb2000-sudo** [comment]
Hey @rahuldhangar  you can send screenshots in comment.

**Comment by deb2000-sudo** [comment]
@calderaricaio it will be great if you send designs .

**Comment by calderaricaio** [comment]
Sure I can do it, just need to know, what would be the page structure and links? do you have social networks you want to add to the footer as well? Any design guideline we need to follow?

**Comment by rahuldhangar** [comment]
@deb2000-sudo Here's a codepen I built, with a simple hover animation. Please check it here: [CodePen - Rahul Dhangar](https://codepen.io/rahuldhangar/pen/abZorXN)

![image](https://user-images.githubusercontent.com/7106661/95246659-6b81fc80-0832-11eb-80fc-6b39150a9792.png)

Please let me know if this works for you (and any instructions to follow)

**Comment by Aniket762** [comment]
Hey @rahuldhangar , this looks good 😀. But something out of the box any other design may be.

**Comment by rahuldhangar** [comment]
@Aniket762 Check this screenshot out:
![image](https://user-images.githubusercontent.com/7106661/95247276-493cae80-0833-11eb-9a12-083fddb494b8.png)

The Car and Bicycle shown in it are animated (they travel left to right at different pace)

**Comment by Aniket762** [comment]
Damn 🔥🔥 this will be great 😍

@rahuldhangar can you just create a pull with the code snippets

**Comment by rahuldhangar** [comment]
> Damn 🔥🔥 this will be great 😍
> 
> @rahuldhangar can you just create a pull with the code snippets

Surely @Aniket762 Please can you instruct me on the data/links/text to be populated in the mentioned columns (Get in Touch, Download, Help, Team Solutions) ?
I will create a PR as soon as I receive your response over this

**Comment by Aniket762** [comment]
@rahuldhangar  For now keep exact when we need to change something we will do not a big issue. I like the animation part 

I am assigning you with this issue! Okay?

**Comment by rahuldhangar** [comment]
> @rahuldhangar For now keep exact when we need to change something we will do not a big issue. I like the animation part
> 
> I am assigning you with this issue! Okay?

@Aniket762  Yes please assign it to me. I am working on the code right now and will do PR soon
