### ISSUE TITLE
Certificate templates

### ISSUE THREAD

**Issue by Aniket762** [Webwiznitr/Project-celadon#7]
First add screenshots of the template  if verified create the PR and send the jpg or png file

**Comment by calderaricaio** [comment]
I can send some ideas.

**Comment by rahuldhangar** [comment]
@Aniket762  I am interested in adding some. But can you tell me how to verify first before creating PR?

**Comment by deb2000-sudo** [comment]
@calderaricaio we are waiting for your ideas.

**Comment by deb2000-sudo** [comment]
@rahuldhangar you can send those templates to be verified over here.

**Comment by calderaricaio** [comment]
Sure, I will send it soon! If you want to give me info about it I can be more assertive with the details.

**Comment by Aniket762** [comment]
Hey @calderaricaio, please try to generate templates in which name of the person , event name , date and signature can be included. Simple designs would work 😁

**Comment by calderaricaio** [comment]
Here are a few options.
We can have a base template and change fonts and background with photos from Unsplash, this way we have endless possibilities.

![certificate-model-2-1](https://user-images.githubusercontent.com/542722/95270518-00c0c900-0812-11eb-8849-4a01f7248863.png)
![certificate-model-2-2](https://user-images.githubusercontent.com/542722/95270519-01f1f600-0812-11eb-9d2b-838e8f903ab2.png)
![certificate-1](https://user-images.githubusercontent.com/542722/95270508-fb637e80-0811-11eb-8db6-bf9c21acc117.png)
![certificate-2](https://user-images.githubusercontent.com/542722/95270515-ff8f9c00-0811-11eb-858b-3f67d7ec694c.png)
![certificate-3](https://user-images.githubusercontent.com/542722/95270516-00283280-0812-11eb-9cb8-25f9f8fc9a03.png)

**Comment by Aniket762** [comment]
@calderaricaio  Awsome 😍 

can you just create a PR with the jpg or png files of the certificates?

**Comment by calderaricaio** [comment]
Hi I've been busy but I will send it soon!

**Comment by calderaricaio** [comment]
Also if you can, please assign it to me. Thanks!

**Comment by calderaricaio** [comment]
I sent the pull request with the certificate images and templates.
