### ISSUE TITLE
Design the homepage for certificate generator 

### ISSUE THREAD

**Issue by Aniket762** [Webwiznitr/Project-celadon#8]
Except the header and footer design the layout

**Comment by calderaricaio** [comment]
Hi I can help with it! Just give me a few days. If you want to give me more information about what you need it will also be helpful to design it.

**Comment by Aniket762** [comment]
@calderaricaio Sure man go for it, it will be really appreciated if you can give it within 2 days😁

**Comment by calderaricaio** [comment]
It would be great to see now the header and footer so we can match the same style.

**Comment by calderaricaio** [comment]
Here's one suggestion (wireframe). We can improve it...
![wireframe-home-page](https://user-images.githubusercontent.com/542722/95271285-e4259080-0813-11eb-9171-d8faaa352cb8.jpg)

**Comment by Aniket762** [comment]
@calderaricaio man this looks amazing 😍 

But I thought of including another option in which people can choose from different templates available can you include that button somewhere?

**Comment by Aniket762** [comment]
@calderaricaio you can check the readme the header and footer are been added and the screenshot is being put up

**Comment by Aniket762** [comment]
> It would be great to see now the header and footer so we can match the same style.

you can check the readme the header and footer are been added and the screenshot is being put up

**Comment by calderaricaio** [comment]
Hi! Sorry I've been busy but I will update it and send it soon!
If you can, please share some screenshots with the current header and footer (not a gif) so I could place them in the example I'm going to send soon.
Also if you want, I can create a simple logo. Just open another Issue for that. Thanks.

**Comment by calderaricaio** [comment]
Also if you can, please assign it to me. Thanks!

**Comment by Aniket762** [comment]
> Hi! Sorry I've been busy but I will update it and send it soon!
> If you can, please share some screenshots with the current header and footer (not a gif) so I could place them in the example I'm going to send soon.
> Also if you want, I can create a simple logo. Just open another Issue for that. Thanks.

https://webwiznitr.github.io/Project-celadon/ you can check the site here and I am opening another issue for logo😀

**Comment by deb2000-sudo** [comment]
@calderaricaio can you give updates about design of homepage

**Comment by calderaricaio** [comment]
I’ll be sending it soon!

**Comment by calderaricaio** [comment]
Hi! Home page is ready!

![Home-Page](https://user-images.githubusercontent.com/542722/96063201-cbe5ef00-0e6d-11eb-82b6-86375feeffa5.png)


And I also created the asset states:

![Home-Page-Assets-States](https://user-images.githubusercontent.com/542722/96063214-d3a59380-0e6d-11eb-8734-d1027461a1b4.png)



I will also send a Figma file link so you can get the Design specs from it.

I'm waiting the approval of my open PR so I can create a new one with the home page files. Thanks.

**Comment by Aniket762** [comment]
Hey @calderaricaio Awsome job dude 😍 please create the PR

**Comment by calderaricaio** [comment]
@Aniket762 Hi! I've added the Pull Request now.
https://github.com/Webwiznitr/Project-celadon/pull/29

Soon I will open a new PR with the logo.

Thanks!
